name: payflow
description: PayFlow App
publish_to: 'none'
version: 2.0.1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  animated_card: ^2.0.0
  camera: ^0.11.0+2
  cupertino_icons: ^1.0.8
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_masked_text2: ^0.9.1
  font_awesome_flutter: ^10.7.0
  google_fonts: ^6.2.1
  google_mlkit_barcode_scanning: ^0.12.0
  google_sign_in: ^6.2.1
  google_sign_in_web: ^0.12.4
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.5
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  image_path: "assets/images/logofull.png"
  image_path_android: "assets/images/logofull.png"
  image_path_ios: "assets/images/logofull.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
