name: payflow
description: PayFlow App
publish_to: 'none'
version: 2.0.0

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  animated_card: ^2.0.0
  camera: ^0.10.2+1
  cupertino_icons: ^1.0.2
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.11.0
  flutter_masked_text2: ^0.9.1
  font_awesome_flutter: ^10.3.0
  google_fonts: ^3.0.1
  google_ml_kit: ^0.13.0
  google_sign_in: ^5.4.3
  google_sign_in_web: ^0.10.0
  google_sign_in_web_redirect: ^0.0.1
  image_picker: ^0.8.6+1
  image_picker_for_web: ^2.1.10
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_icons:
  image_path: "assets/images/logofull.png"
  image_path_android: "assets/images/logofull.png"
  image_path_ios: "assets/images/logofull.png"
  android: true
  ios: true
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/icon-1024x1024.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
