// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpmYKtwuR0i-2z9e0GuklRxK0oCY900EA',
    appId: '1:729322644360:android:119258b076855540e7903d',
    messagingSenderId: '729322644360',
    projectId: 'payflow-e9031',
    storageBucket: 'payflow-e9031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqaqkpt-mf3OIYey0FOBloURmGLkxqN7Y',
    appId: '1:729322644360:ios:a9335a23edeed249e7903d',
    messagingSenderId: '729322644360',
    projectId: 'payflow-e9031',
    storageBucket: 'payflow-e9031.appspot.com',
    androidClientId: '729322644360-llus2au7g894p00i74s1b6ehvfhbhnk5.apps.googleusercontent.com',
    iosClientId: '729322644360-u5mn7hlr17h5e04piolpf8pshq5b3uc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.payflow',
  );
}
